# Generated by Django 5.1.7 on 2025-03-20 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item_userinformation_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20, validators=[django.core.validators.MinLengthValidator(10)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='password',
            field=models.TextField(default='default_password', max_length=255),
            preserve_default=False,
        ),
    ]
