# Generated by Django 5.1.7 on 2025-03-31 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userinformation_phone_alter_userinformation_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='password',
        ),
    ]
