# Generated by Django 5.2 on 2025-04-10 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=60)),
        ),
    ]
