# Generated by Django 5.2 on 2025-04-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_exam_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id_question', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.IntegerField(choices=[(10, 'Lớp 10'), (11, 'Lớp 11'), (12, 'Lớp 12')])),
                ('question_format', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('midterm', 'Giữa kỳ'), ('final', 'Cuối kỳ')], max_length=10)),
                ('difficulty', models.IntegerField(choices=[(1, 'Nhận biết'), (2, 'Thông hiểu'), (3, 'Vận dụng'), (4, 'Vận dụng cao')])),
                ('content', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='exam',
            name='subject',
        ),
        migrations.AddField(
            model_name='exam',
            name='grade',
            field=models.IntegerField(choices=[(10, 'Lớp 10'), (11, 'Lớp 11'), (12, 'Lớp 12')], default=10),
            preserve_default=False,
        ),
    ]
