# Generated by Django 5.2 on 2025-04-10 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_examquestion_remove_exam_subject_exam_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.exam'),
        ),
    ]
