# Generated by Django 5.2 on 2025-04-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_examquestion_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.IntegerField(default=3600),
        ),
    ]
