# Generated by Django 5.1.7 on 2025-05-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_exam_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='duration',
        ),
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('active', 'Đang diễn ra'), ('upcoming', 'Chưa bắt đầu'), ('finished', 'Đã kết thúc')], default='upcoming', max_length=10),
        ),
        migrations.AlterField(
            model_name='exam',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
