# Generated by Django 5.1.7 on 2025-05-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_exam_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('active', 'Đang diễn ra'), ('upcoming', 'Chưa bắt đầu'), ('finished', 'Đã kết thúc')], default='upcoming', max_length=20),
        ),
    ]
