# Generated by Django 5.1.7 on 2025-05-27 17:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_exam_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file_url', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, choices=[('10', 'Lớp 10'), ('11', 'Lớp 11'), ('12', 'Lớp 12')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tài liệu',
                'verbose_name_plural': 'Danh sách tài liệu',
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='ExamShift',
            fields=[
                ('shift_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exam')),
            ],
            options={
                'verbose_name': 'Kíp thi',
                'verbose_name_plural': 'Danh sách kíp thi',
                'db_table': 'exam_shift',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('grade', models.CharField(choices=[('10', 'Lớp 10'), ('11', 'Lớp 11'), ('12', 'Lớp 12')], max_length=20)),
                ('duration_minutes', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.CharField(choices=[('basic', 'Cơ bản'), ('medium', 'Trung bình'), ('hard', 'Khó')], max_length=10, null=True)),
                ('doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.document')),
                ('shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.examshift')),
            ],
            options={
                'verbose_name': 'Bài thi',
                'verbose_name_plural': 'Danh sách bài thi',
                'db_table': 'tests',
            },
        ),
    ]
