# Generated by Django 5.1.7 on 2025-05-29 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_exam_user_document_examshift_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Chủ đề',
                'verbose_name_plural': 'Danh sách chủ đề',
                'db_table': 'topics',
            },
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Đề thi', 'verbose_name_plural': 'Danh sách đề thi'},
        ),
        migrations.AlterField(
            model_name='test',
            name='level',
            field=models.CharField(choices=[('Cơ bản', 'Cơ bản'), ('Trung bình', 'Trung bình'), ('Khó', 'Khó')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='ExamTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exam')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.topic')),
            ],
            options={
                'verbose_name': 'Kỳ thi - Chủ đề',
                'verbose_name_plural': 'Danh sách kỳ thi - chủ đề',
                'db_table': 'exam_topic',
                'unique_together': {('exam', 'topic')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.topic'),
        ),
        migrations.AddField(
            model_name='exam',
            name='topics',
            field=models.ManyToManyField(related_name='exams', through='api.ExamTopic', to='api.topic'),
        ),
    ]
