# Generated by Django 5.1.7 on 2025-05-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_topic_alter_test_options_alter_test_level_examtopic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='level',
            field=models.CharField(blank=True, choices=[('basic', 'Cơ bản'), ('intermediate', 'Trung bình'), ('advanced', 'Khó')], max_length=20, null=True),
        ),
    ]
