# Generated by Django 5.1.7 on 2025-06-02 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_document_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='test',
            name='grade',
        ),
        migrations.AddField(
            model_name='test',
            name='type',
            field=models.CharField(choices=[('Thi thử', 'Thi thử'), ('Thi thật', 'Thi thật')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
