# Generated by Django 5.1.7 on 2025-06-02 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_test_doc_remove_test_grade_test_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='level',
        ),
    ]
