# Generated by Django 5.1.7 on 2025-06-02 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_test_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('single', 'Trắc nghiệm 1 đáp án'), ('multiple', 'Trắc nghiệm nhiều đáp án'), ('text', 'Tự luận')], max_length=20)),
                ('score', models.FloatField()),
                ('level', models.IntegerField()),
                ('is_gened_by_model', models.BooleanField(default=False)),
                ('created_by_question', models.BooleanField(default=False)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.test')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Câu hỏi',
                'verbose_name_plural': 'Danh sách câu hỏi',
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.question')),
            ],
            options={
                'verbose_name': 'Đáp án',
                'verbose_name_plural': 'Danh sách đáp án',
                'db_table': 'answers',
            },
        ),
    ]
