# Generated by Django 5.1.7 on 2025-06-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examshift',
            name='date',
        ),
        migrations.RemoveField(
            model_name='examshift',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='examshift',
            name='name',
        ),
        migrations.RemoveField(
            model_name='examshift',
            name='start_time',
        ),
        migrations.AddField(
            model_name='exam',
            name='regrade_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='regrade_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examshift',
            name='end_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='examshift',
            name='start_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
