# Generated by Django 5.1.7 on 2025-06-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_examshift_date_remove_examshift_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examshift',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='examshift',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='examshift',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='examshift',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
