# Generated by Django 5.1.7 on 2025-06-03 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_examshift_end_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examshift',
            name='exam',
        ),
    ]
