# Generated by Django 5.1.7 on 2025-06-03 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_examshift_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.exam'),
        ),
    ]
