# Generated by Django 5.1.7 on 2025-06-05 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_test_exam'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('student_answer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='api.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='api.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='api.test')),
            ],
            options={
                'verbose_name': 'Câu trả lời của sinh viên',
                'verbose_name_plural': 'Danh sách câu trả lời sinh viên',
                'db_table': 'student_answer',
                'unique_together': {('student', 'test', 'question')},
            },
        ),
    ]
