# Generated by Django 5.1.7 on 2025-06-05 19:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_studentanswer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_url',
            field=models.FileField(upload_to=api.models.upload_to_documents),
        ),
    ]
