# Generated by Django 5.2.1 on 2025-06-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_document_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='image_question/'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='answer_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
