# Generated by Django 5.1.7 on 2025-06-22 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_result'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReviewTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm gửi yêu cầu')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Điểm số hiện tại')),
                ('reason', models.TextField(verbose_name='Lý do xin phúc tra')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_review_tests', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_requests', to=settings.AUTH_USER_MODEL, verbose_name='Giáo viên tạo đề thi')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_review_tests', to='api.test')),
            ],
            options={
                'verbose_name': 'Phúc tra bài thi (sinh viên)',
                'verbose_name_plural': 'Danh sách phúc tra bài thi (sinh viên)',
                'db_table': 'student_review_test',
                'unique_together': {('student', 'test')},
            },
        ),
        migrations.CreateModel(
            name='TeacherReviewTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm phúc tra')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Điểm số cuối cùng sau phúc tra')),
                ('reason', models.TextField(verbose_name='Ghi chú/lý do của giáo viên')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handled_review_tests', to=settings.AUTH_USER_MODEL, verbose_name='Học sinh được phúc tra')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_review_tests', to=settings.AUTH_USER_MODEL, verbose_name='Giáo viên xử lý phúc tra')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_review_tests', to='api.test')),
            ],
            options={
                'verbose_name': 'Phúc tra bài thi (giáo viên)',
                'verbose_name_plural': 'Danh sách phúc tra bài thi (giáo viên)',
                'db_table': 'teacher_review_test',
                'unique_together': {('test', 'teacher')},
            },
        ),
    ]
