# Generated by Django 5.1.7 on 2025-06-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_question_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(blank=True, choices=[('single', 'Trắc nghiệm 1 đáp án'), ('multiple', 'Trắc nghiệm nhiều đáp án'), ('text', 'Tự luận')], max_length=20, null=True),
        ),
    ]
