# Generated by Django 5.1.7 on 2025-07-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_userinformation_user_alter_userinformation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='user',
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
