# Generated by Django 5.1.7 on 2025-07-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_userinformation_user_alter_userinformation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
    ]
