# Generated by Django 5.1.7 on 2025-07-06 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_studentprofile_teacherprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
